export declare function isNil(obj: any): obj is null | undefined;
export declare function isNilOrFalse(obj: any): obj is null | undefined | false;
export declare function isTrue(obj: any): obj is true;
export declare function isObject(obj: any): obj is Object;
export declare function isError(obj: any): obj is Error;
export declare function isNode(obj: any): obj is Node;
export declare function isRegExp(obj: any): obj is RegExp;
export declare function isDate(obj: any): obj is Date;
export declare function isWindow(obj: any): obj is Window;
export declare function isDocument(obj: any): obj is Document;
export declare function isDocumentFragment(obj: any): obj is DocumentFragment;
export declare function isFile(obj: any): obj is File;
export declare function isFunction(obj: any): obj is Function;
export declare function isArray(obj: any): obj is any[];
export declare function isString(obj: any): obj is string;
export declare function toNumber(value: any): number;
export declare function toNumber(...values: any[]): number[];
export declare function isFiniteNumber(obj: any): obj is number;
export declare function isPromise(obj: any): obj is Promise<any>;
export declare function isObjectNotEmpty(obj: any): obj is {
    [key: string]: any;
};
export declare function isArrayLike(obj: any): obj is ArrayLike<any>;
export declare function isArrayNotEmpty(obj: any): obj is ArrayLike<any>;
export declare function isNotEmpty(obj: any): ReturnType<typeof isObjectNotEmpty | typeof isArrayNotEmpty>;
export declare function isPrimitive(obj: any): obj is number | string | null;
export declare function isImmutable(obj: any): obj is RegExp | number;
export declare function isMutable(obj: any): obj is Date;
export declare function isSymbol(obj: any): obj is symbol;
export declare function isSamePropertyDescriptor(a?: PropertyDescriptor, b?: PropertyDescriptor): boolean;
